### PR TITLE
Add instructions to create volume for uploads

### LINKED ISSUE #18: Backup upload images
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

## Expected Behavior

When I restart container I would like display uploaded picture.

## Current Behavior

When I restart container all picture uploaded are deleted.

## Steps to Reproduce

1. Create a note on hedgedoc
2. Upload picture on this note
3. Restart container
4. Picture not display

On documentation you should attach volume on /path/to/config:/opt/hedgedoc/public/uploads

### PR DESCRIPTION
**Pull request by thomaswucher**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-hedgedoc/blob/main/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

This fixes #18. Leaving out the docker volume for uploads will remove all 
uploaded attachments on container updates, causing a loss of production data.

## Benefits of this PR and context:

Data loss is bad so we should prevent it.

## How Has This Been Tested?

I restarted the container and I still have my uploads.

### CODE REVIEW

**Comment by thomaswucher** [comment]
Ping @aptalca

**Comment by Roxedus** [comment]
This is not the way to change the readme, it will not last. there's a short explanation in the contributing file you claim to have read.

**Comment by thomaswucher** [comment]
Well then, here you go. Maybe don't wait 8 days to mention a single mistake. I wouldn't have had to jump through these hoops in the first if #18 would have been triaged in a timely.

**Comment by Roxedus** [comment]
Sorry for trying my best to keep up with all prs and issues?

**Comment by thomaswucher** [comment]
Thanks for taking a look at this, I know you are doing this for free and that's awesome. Sometimes it can just be a little bit frustrating, when no one seems to care (even if that's not true, I know).

**Comment by aptalca** [comment]
Just being honest. . . Those types of comments generally make me push those issues/PRs further down on my ridiculously long to do list. We are all volunteers here and we all have jobs and lives outside of this.

But I'm just one person. Maybe someone else on the team will be motivated to look into it.

**Comment by aptalca** [comment]
posted my message before I saw your last one. In any case, we are not ignoring. We just have a really long list of issues to deal with: https://github.com/orgs/linuxserver/projects/3

**Pull request closed without merging**
